steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -f
      - cloud-run/Dockerfile
      - -t
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_SERVICE}:latest
      - .
images:
  - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_SERVICE}:latest
substitutions:
  _REGION: europe-west1
  _REPOSITORY: boulangerie-lomoto
  _SERVICE: boulangerie-lomoto-api
